2016-11-02 22:45:14,671 INFO     BEGIN
2016-11-02 22:45:14,672 INFO     struct {
    trainer:
        improvement_threshold: 0.8
        use_curriculum: True
        name: 'CurriculumTrainer'
        max_timesteps: 100
        hints: 'resources/light/hints.yaml'
    name: 'light_joint-feat-plan'
    recipes: 'resources/craft/recipes.yaml'
    world:
        name: 'LightWorld'
    model:
        baseline: 'state'
        use_args: False
        name: 'ModularACModel'
        max_subtask_timesteps: 15
        featurize_plan: True
    experiment_dir: 'experiments/light_joint-feat-plan'
}
2016-11-02 22:45:45,472 INFO     [max steps] 1
2016-11-02 22:45:45,472 INFO     [min reward] inf
2016-11-02 22:45:45,472 INFO     
2016-11-02 22:45:59,607 INFO     [max steps] 2
2016-11-02 22:45:59,609 ERROR    Uncaught exception: None
None
2016-11-02 22:45:59,610 ERROR    Traceback (most recent call last):

  File "main.py", line 50, in <module>
    main()

  File "main.py", line 22, in main
    trainer.train(model, world)

  File "/home/ubuntu/craft/trainers/curriculum.py", line 150, in train
    possible_tasks, task_probs)

  File "/home/ubuntu/craft/trainers/curriculum.py", line 66, in do_rollout
    scenario = world.sample_scenario_with_goal(goal_arg)

  File "/home/ubuntu/craft/worlds/light.py", line 22, in sample_scenario_with_goal
    goal = self.cookbook.index.get(goal)

  File "/home/ubuntu/craft/misc/util.py", line 62, in get
    return self.reverse_contents[idx]

KeyError: None
None
